OUTPUT_DIR: "/ghome/group03/mcv-m6-2023-team6/week5/Results/end2end/byTrack/AI_city_S04_ByTrack"
DEBUG_RUN: false
FONTSIZE: 15
MOT:
  TRACKED_CLASSES: [2, 7] # ["cars", "truck"] [1, 2, 3, 5, 7]
  REID_MODEL_OPTS: "vehicle_models/resnet50_mixstyle/opts.yaml"
  REID_MODEL_CKPT: "vehicle_models/resnet50_mixstyle/net_19.pth"
  REID_FP16: false
  REID_BATCHSIZE: 1
  DETECTOR: "yolov8"
  TRACKER: "bytetrack_iou"
  MIN_FRAMES: 10
  SHOW: false
  VIDEO_OUTPUT: true
  STATIC_ATTRIBUTES:
    - color: "vehicle_models/color_svm.pkl"
    - type: "vehicle_models/type_svm.pkl"
  REFINE: false
  # VALID_ZONEPATHS: ["1,.*,2", "2,.*, 1", "3, .*,4", "4, .*, 3", "5, .*, 5"]
MTMC:
  CAMERA_LAYOUT: 'config/AI_city/s04_camera_layout.txt'
  LINKAGE: 'mean_feature'
  MIN_SIM: 0.5
EXPRESS:
  FINAL_VIDEO_OUTPUT: true
  CAMERAS:
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c016/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c016/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c016/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c017/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c017/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c017/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c018/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c018/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c018/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c019/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c019/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c019/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c020/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c020/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c020/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c021/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c021/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c021/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c022/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c022/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c022/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c023/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c023/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c023/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c024/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c024/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c024/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c025/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c025/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c025/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c026/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c026/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c026/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c027/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c027/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c027/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c028/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c028/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c028/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c029/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c029/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c029/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c030/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c030/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c030/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c031/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c031/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c031/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c032/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c032/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c032/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c033/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c033/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c033/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c034/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c034/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c034/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c035/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c035/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c035/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c036/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c036/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c036/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c037/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c037/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c037/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c038/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c038/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c038/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c039/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c039/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c039/calibration.txt"
    - "video": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c040/vdo.avi"
      "detection_mask": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c040/roi.jpg"
      "calibration": "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c040/calibration.txt"

EVAL:
  MIN_IOU: 0.5
  IGNORE_FP: true
  DROP_SINGLE_CAM: false
  GROUND_TRUTHS:
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c016/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c017/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c018/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c019/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c020/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c021/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c022/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c023/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c024/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c025/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c026/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c027/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c028/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c029/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c030/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c031/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c032/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c033/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c034/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c035/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c036/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c037/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c038/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c039/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c040/gt/gt.txt'
