OUTPUT_DIR: "/ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou/AI_city_s03_maxiou"
MTMC:
  CAMERA_LAYOUT: 'config/AI_city/s03_camera_layout.txt'
  PICKLED_TRACKLETS:
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S03/mot_features_c010.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S03/mot_features_c011.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S03/mot_features_c012.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S03/mot_features_c013.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S03/mot_features_c014.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S03/mot_features_c015.pkl"

  LINKAGE: 'mean_feature'
  MIN_SIM: 0.5
EVAL:
  MIN_IOU: 0.5
  IGNORE_FP: true
  DROP_SINGLE_CAM: false
  GROUND_TRUTHS:
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c010/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c011/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c012/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c013/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c014/gt/gt.txt"
    - "/export/home/group03/dataset/aic19-track1-mtmc-train/train/S03/c015/gt/gt.txt"
