OUTPUT_DIR: "/ghome/group03/mcv-m6-2023-team6/week5/Results/from_our_trackers/max_iou/AI_city_s04_maxiou"
MTMC:
  CAMERA_LAYOUT: 'config/AI_city/s04_camera_layout.txt'
  PICKLED_TRACKLETS:
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c016.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c017.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c018.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c019.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c020.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c021.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c022.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c023.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c024.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c025.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c026.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c027.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c028.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c029.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c030.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c031.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c032.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c033.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c034.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c035.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c036.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c037.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c038.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c039.pkl"
    - "/ghome/group03/mcv-m6-2023-team6/week5/Results/trackings/MTSC/max_iou/mot/S04/mot_features_c040.pkl"
  LINKAGE: 'mean_feature'
  MIN_SIM: 0.5
EVAL:
  MIN_IOU: 0.5
  IGNORE_FP: true
  DROP_SINGLE_CAM: false
  GROUND_TRUTHS:
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c016/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c017/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c018/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c019/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c020/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c021/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c022/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c023/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c024/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c025/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c026/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c027/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c028/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c029/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c030/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c031/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c032/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c033/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c034/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c035/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c036/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c037/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c038/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c039/gt/gt.txt'
    - '/export/home/group03/dataset/aic19-track1-mtmc-train/train/S04/c040/gt/gt.txt'
